services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: mark-III-app
    working_dir: /var/www
    volumes:
      - ./src:/var/www
      # - ./src/public:/var/www/public
    networks:
      - laravel
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    container_name: mark-III-nginx
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    depends_on:
      - app

  mysql:
    image: mysql:8
    container_name: mark-III-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: todo_app
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    container_name: mark-III-phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    networks:
      - laravel
    ports:
      - 8001:80

  phpmyadmin:
    depends_on:
        - mysql
    image: phpmyadmin/phpmyadmin
    container_name: mark-II-phpmyadmin
    environment:
        - PMA_HOST=mysql
        - PMA_PORT=3306
    networks:
        - laravel
    ports:
        - 8001:80

networks:
  laravel:

volumes:
  mysql_data:

